make redhat conversion tool downloadable with Pip
ossf/osv-schema pull request #278
Opened 2024-09-12 02:16 UTC by jasinner

In order to install the Red Hat converter tool via Pip we need a setup.py. Adding that here.

This change avoids specifying the runtime dependencies in both Pipenv and setup.py by requesting users install the module locally with:

`pipenv install -e .`

As specified in the updated README.md

2024-09-12 04:43 UTC, andrewpollock requested changes
Looks like there's a little bit of copy pasta left over?

2024-09-12 04:43 UTC, andrewpollock commented on tools/redhat/setup.py
> +    description="Newtopia CLI v1",
Copy pasta?

```suggestion
    description="Convert a Red Hat CSAF document to OSV format",
```

2024-09-12 04:43 UTC, andrewpollock commented on tools/redhat/setup.py
> +    keywords=["Swagger", "Newtopia CLI v1"],
Maybe this instead?

```suggestion
    keywords=["OSV", "JSON", "Conversion"],
```

2024-09-12 04:43 UTC, andrewpollock commented on tools/redhat/setup.py
> +    The purpose of this CLI is to interact with the manifest and dependency information API from the Deptopia project, and Manifest box repo.  # noqa: E501
Fix copy pasta

```suggestion
    The purpose of this tool is to convert from CSAF documents to OSV # noqa: E501
```

2024-09-12 05:19 UTC, jasinner commented
Sorry about that. I've updated the value to be specific to this module as per your suggestions.

2024-09-12 05:28 UTC, jasinner commented
Justing putting this in Draft while I attempt to import it using Pip in another project.

2024-09-13 01:13 UTC, jasinner commented
> Just putting this in Draft while I attempt to import it using Pip in another project.

Ok, I had to move things around a little bit, but this is importing successfully with Pip now. @andrewpollock can you please have another look and merge if you're happy.

2024-09-13 03:32 UTC, andrewpollock approved these changes

2024-09-13 03:32 UTC, merged